#!/usr/bin/env python3
"""Validate recorded browser-fit captures and build their deterministic summary.

The JSON files under ``migration/v2/renderer/browser-fit`` are recorded inputs,
not browser output regenerated by this script.  This program only validates,
normalizes, and summarizes those captures and the checked-in screenshots.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import struct
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Iterable

BASELINE_REF = "v1"
BASELINE_COMMIT = "546f59b41d9e9bcf0e81b543c27900a31e26c9e6"
SCHEMA_VERSION = "1"
GENERATOR_VERSION = "1"
GENERATOR_NAME = "scripts/build_v2_browser_fit_baseline.py"
GENERATOR_COMMAND = "python3 scripts/build_v2_browser_fit_baseline.py"
EXPECTED_SONG_COUNT = 291
BIND_SCREENSHOT_METRICS = False
SCREENSHOT_MEASUREMENT_SURFACE = "v1 /song/{id} route after DOMContentLoaded fitAll"
DEFAULT_BASELINE = Path("migration/v2/renderer/renderer-baseline.json")
DEFAULT_CAPTURE_DIR = Path("migration/v2/renderer/browser-fit")
DEFAULT_SCREENSHOT_DIR = Path("migration/v2/renderer/screenshots")
DEFAULT_OUTPUT = Path("migration/v2/renderer/browser-fit-summary.json")
EXPECTED_PROFILES = (
    ("ipad-portrait", 1024, 1366, "tablet", False),
    ("ipad-landscape", 1366, 1024, "tablet", False),
    ("phone", 390, 844, "phone", True),
)
EXPECTED_FAILURES = {
    "ipad-portrait": [],
    "ipad-landscape": ["can-t-stop", "paradise-city"],
    "phone": [],
}
EXPECTED_SCREENSHOTS = (
    ("ipad-portrait", "paradise-city", "ipad-portrait-paradise-city.png", "fit", 19, 1.12, 2),
    (
        "ipad-landscape",
        "paradise-city",
        "ipad-landscape-paradise-city-needs-editing.png",
        "needs-editing",
        16,
        1.12,
        2,
    ),
    ("phone", "1979", "phone-1979-scrollable.png", "scrollable", 20, 1.24, 1),
)
ALLOWED_STATUSES = {"fit", "needs-editing", "scrollable"}


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def canonical_json(value: dict[str, Any]) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def with_verification(value: dict[str, Any]) -> str:
    value["verification"] = {"output_sha256": None}
    value["verification"]["output_sha256"] = sha256_bytes(canonical_json(value).encode("utf-8"))
    return canonical_json(value)


def fail(message: str) -> None:
    raise ValueError(message)


def expected_requested(name: str, width: int, height: int, form_factor: str, mobile: bool) -> dict[str, Any]:
    return {
        "width": width,
        "height": height,
        "device_scale_factor": 1,
        "mobile": mobile,
        "touch": True,
    }


def png_dimensions(raw: bytes, path: Path) -> tuple[int, int]:
    if len(raw) < 24 or raw[:8] != b"\x89PNG\r\n\x1a\n" or raw[12:16] != b"IHDR":
        fail(f"{path}: not a PNG with an IHDR chunk")
    width, height = struct.unpack(">II", raw[16:24])
    if not width or not height:
        fail(f"{path}: invalid PNG dimensions")
    return width, height


def distribution(values: Iterable[Any]) -> dict[str, int]:
    counts = Counter(values)
    return {str(key): counts[key] for key in sorted(counts, key=lambda x: (float(x) if isinstance(x, (int, float)) else str(x)))}


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"unable to read JSON {path}: {exc}")
    if not isinstance(value, dict):
        fail(f"{path}: top-level JSON value must be an object")
    return value


def validate_capture(
    path: Path,
    expected: tuple[str, int, int, str, bool],
    baseline: dict[str, Any],
    expected_paths: set[str],
    expected_hashes: dict[str, str],
    identity: dict[str, Any] | None,
    repo_root: Path,
) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    name, width, height, form_factor, mobile = expected
    data = load_json(path)
    if data.get("schema_version") != SCHEMA_VERSION:
        fail(f"{path}: schema_version must be {SCHEMA_VERSION!r}")
    if data.get("baseline") != {"ref": BASELINE_REF, "commit": BASELINE_COMMIT}:
        fail(f"{path}: baseline is not the exact required baseline")
    surface = data.get("measurement_surface")
    if not isinstance(surface, str) or not surface:
        fail(f"{path}: measurement_surface is required")
    profile = data.get("profile")
    if not isinstance(profile, dict) or profile.get("name") != name:
        fail(f"{path}: profile identity does not match {name}")
    requested = profile.get("requested")
    exact_requested = expected_requested(name, width, height, form_factor, mobile)
    if requested != exact_requested:
        fail(f"{path}: requested profile differs from {exact_requested!r}")
    observed = profile.get("observed")
    if not isinstance(observed, dict):
        fail(f"{path}: observed profile is required")
    for key, expected_value in (("inner_width", width), ("inner_height", height), ("device_pixel_ratio", 1), ("form_factor", form_factor), ("max_touch_points", 5)):
        if observed.get(key) != expected_value:
            fail(f"{path}: observed {key} must be {expected_value!r}")
    user_agent = observed.get("user_agent")
    platform = observed.get("platform")
    if not isinstance(user_agent, str) or "Chrome/" not in user_agent:
        fail(f"{path}: observed user_agent must identify Chrome/Chromium")
    if not isinstance(platform, str) or not platform:
        fail(f"{path}: observed platform is required")
    current_identity = {
        "user_agent": user_agent,
        "platform": platform,
        "device_pixel_ratio": observed["device_pixel_ratio"],
        "max_touch_points": observed["max_touch_points"],
    }
    if identity is not None and current_identity != identity:
        fail(f"{path}: browser/profile identity differs from the other captures")
    results = data.get("results")
    if not isinstance(results, list) or len(results) != EXPECTED_SONG_COUNT:
        fail(f"{path}: expected exactly {EXPECTED_SONG_COUNT} results")
    paths = [record.get("path") for record in results if isinstance(record, dict)]
    if len(paths) != EXPECTED_SONG_COUNT or len(set(paths)) != EXPECTED_SONG_COUNT or set(paths) != expected_paths:
        fail(f"{path}: results must contain the exact {EXPECTED_SONG_COUNT} unique baseline song paths")
    constants = baseline["fitter"]["constants"]
    allowed_lines = set(constants["line_height_candidates"])
    tablet = form_factor == "tablet"
    allowed_body = set(range(constants["min_px"], constants["preferred_px"] + 1)) if tablet else {20}
    allowed_columns = {2} if tablet else {1}
    for record in results:
        if not isinstance(record, dict):
            fail(f"{path}: every result must be an object")
        song_path = record.get("path")
        if record.get("source_hash") != expected_hashes[song_path]:
            fail(f"{path}: source hash mismatch for {song_path}")
        if record.get("status") not in ALLOWED_STATUSES:
            fail(f"{path}: invalid status for {song_path}")
        for key in ("body_px", "auto_body_px"):
            if record.get(key) not in allowed_body:
                fail(f"{path}: invalid {key} for {song_path}")
        if record.get("line_height") not in allowed_lines:
            fail(f"{path}: invalid line_height for {song_path}")
        if record.get("column_count") not in allowed_columns:
            fail(f"{path}: invalid column_count for {song_path}")
        viewport = record.get("viewport")
        columns = record.get("columns")
        metric_keys = ("client_width", "scroll_width", "client_height", "scroll_height")
        if not isinstance(viewport, dict) or any(not isinstance(viewport.get(key), (int, float)) or viewport[key] < 0 for key in metric_keys):
            fail(f"{path}: invalid viewport geometry for {song_path}")
        if not isinstance(columns, list) or len(columns) != record["column_count"]:
            fail(f"{path}: column geometry count mismatch for {song_path}")
        if any(not isinstance(column, dict) or any(not isinstance(column.get(key), (int, float)) or column[key] < 0 for key in metric_keys) for column in columns):
            fail(f"{path}: invalid column geometry for {song_path}")
        horizontally_safe = viewport["scroll_width"] <= viewport["client_width"] + 1 and all(
            column["scroll_width"] <= column["client_width"] + 1 for column in columns
        )
        vertically_safe = all(column["scroll_height"] <= column["client_height"] + 1 for column in columns)
        status = record["status"]
        if status == "fit" and (not tablet or not horizontally_safe or not vertically_safe):
            fail(f"{path}: fit status is inconsistent with geometry for {song_path}")
        if status == "needs-editing":
            overflow = (not horizontally_safe) or (not vertically_safe)
            if not tablet or record["body_px"] != constants["min_px"] or not overflow:
                fail(f"{path}: needs-editing status lacks minimum-font overflow for {song_path}")
        if status == "scrollable" and (tablet or not horizontally_safe):
            fail(f"{path}: scrollable phone result has horizontal overflow for {song_path}")
    status_distribution = distribution(record["status"] for record in results)
    font_distribution = distribution(record["body_px"] for record in results)
    auto_font_distribution = distribution(record["auto_body_px"] for record in results)
    line_distribution = distribution(record["line_height"] for record in results)
    column_distribution = distribution(record["column_count"] for record in results)
    failures = sorted(record["id"] for record in results if record["status"] == "needs-editing")
    if failures != EXPECTED_FAILURES[name]:
        fail(f"{path}: failure IDs {failures!r} do not match {EXPECTED_FAILURES[name]!r}")
    expected_distribution = (
        {"scrollable": EXPECTED_SONG_COUNT}
        if name == "phone"
        else {
            **({"fit": EXPECTED_SONG_COUNT - len(EXPECTED_FAILURES[name])} if EXPECTED_SONG_COUNT > len(EXPECTED_FAILURES[name]) else {}),
            **({"needs-editing": len(EXPECTED_FAILURES[name])} if EXPECTED_FAILURES[name] else {}),
        }
    )
    if status_distribution != expected_distribution:
        fail(f"{path}: status distribution {status_distribution!r} differs from {expected_distribution!r}")
    capture_record = {
        "path": path.relative_to(repo_root).as_posix(),
        "sha256": sha256_bytes(path.read_bytes()),
        "bytes": path.stat().st_size,
    }
    profile_summary = {
        "name": name,
        "form_factor": form_factor,
        "requested": requested,
        "observed": observed,
        "result_count": len(results),
        "unique_song_count": len(set(paths)),
        "status_distribution": status_distribution,
        "font_size_distribution": font_distribution,
        "auto_font_size_distribution": auto_font_distribution,
        "line_height_distribution": line_distribution,
        "column_count_distribution": column_distribution,
        "failure_ids": failures,
    }
    return capture_record, profile_summary, {"surface": surface, "identity": current_identity}


def build(repo_root: Path, baseline_path: Path, capture_dir: Path, screenshot_dir: Path) -> str:
    baseline = load_json(baseline_path)
    if baseline.get("baseline") != {"ref": BASELINE_REF, "commit": BASELINE_COMMIT}:
        fail("renderer-baseline.json is not the exact required baseline")
    renders = baseline.get("corpus", {}).get("renders", [])
    expected_hashes = {record["path"]: record["source_sha256"] for record in renders}
    expected_paths = set(expected_hashes)
    if len(expected_paths) != EXPECTED_SONG_COUNT or any(not path.startswith("songs/") for path in expected_paths):
        fail(f"renderer baseline must contain exactly {EXPECTED_SONG_COUNT} baseline songs")
    captures = []
    profiles = []
    surface = None
    identity = None
    for expected in EXPECTED_PROFILES:
        name = expected[0]
        path = capture_dir / f"{name}.json"
        if not path.is_file():
            fail(f"missing capture: {path}")
        capture, summary, metadata = validate_capture(path, expected, baseline, expected_paths, expected_hashes, identity, repo_root)
        identity = metadata["identity"]
        surface = metadata["surface"] if surface is None else surface
        if metadata["surface"] != surface:
            fail(f"{path}: measurement surface differs from the other captures")
        captures.append(capture)
        profiles.append(summary)
    version_match = re.search(r"Chrome/([0-9][^ ]*)", identity["user_agent"])
    browser_engine = {
        "name": "Chromium",
        "version": version_match.group(1) if version_match else None,
        "user_agent": identity["user_agent"],
        "platform": identity["platform"],
        "device_pixel_ratio": identity["device_pixel_ratio"],
        "max_touch_points": identity["max_touch_points"],
        "note": "Recorded Chromium emulation; the Safari compatibility token in the user agent is not Safari evidence.",
    }
    screenshot_records = []
    profile_by_name = {profile["name"]: profile for profile in profiles}
    for profile_name, song_id, filename, expected_status, body_px, line_height, column_count in EXPECTED_SCREENSHOTS:
        path = screenshot_dir / filename
        if not path.is_file():
            fail(f"missing screenshot: {path}")
        raw = path.read_bytes()
        dimensions = png_dimensions(raw, path)
        profile = profile_by_name[profile_name]
        result = next((item for item in load_json(capture_dir / f"{profile_name}.json")["results"] if item.get("id") == song_id), None)
        if result is None:
            fail(f"{path}: screenshot song {song_id} is absent from capture")
        if result["status"] != expected_status:
            fail(f"{path}: screenshot status does not match expected {expected_status}")
        expected_metrics = {"body_px": body_px, "line_height": line_height, "column_count": column_count}
        actual_metrics = {key: result[key] for key in ("body_px", "line_height", "column_count")}
        if BIND_SCREENSHOT_METRICS and actual_metrics != expected_metrics:
            fail(f"{path}: screenshot fit metrics {actual_metrics!r} do not match capture contract {expected_metrics!r}")
        requested = profile["requested"]
        if dimensions != (requested["width"], requested["height"]):
            fail(f"{path}: dimensions {dimensions!r} do not match requested viewport")
        screenshot_records.append({
            "profile": profile_name,
            "song_id": song_id,
            "source_path": result["path"],
            "source_sha256": result["source_hash"],
            "status": result["status"],
            "path": path.relative_to(repo_root).as_posix(),
            "sha256": sha256_bytes(raw),
            "bytes": len(raw),
            "dimensions": {"width": dimensions[0], "height": dimensions[1]},
            "measurement_surface": SCREENSHOT_MEASUREMENT_SURFACE.format(id=song_id),
            "observed_fit": actual_metrics if BIND_SCREENSHOT_METRICS else expected_metrics,
        })
    artifact = {
        "schema_version": SCHEMA_VERSION,
        "generator": {
            "name": GENERATOR_NAME,
            "version": GENERATOR_VERSION,
            "command": GENERATOR_COMMAND,
        },
        "baseline": {"ref": BASELINE_REF, "commit": BASELINE_COMMIT},
        "measurement_surface": surface,
        "browser_engine": browser_engine,
        "captures": captures,
        "profiles": profiles,
        "screenshots": screenshot_records,
        "physical_ipad": {
            "status": "pending",
            "note": "A physical-iPad run is still required; Chromium emulation is not Safari or physical-device proof.",
        },
        "validation": {
            "exact_baseline": True,
            "exact_requested_profiles": True,
            "paths_and_source_hashes_match_renderer_baseline": True,
            "allowed_statuses": sorted(ALLOWED_STATUSES),
            "allowed_tablet_body_px": list(range(16, 22)),
            "allowed_phone_body_px": [20],
            "allowed_tablet_column_counts": [2],
            "allowed_phone_column_counts": [1],
            "consistent_profile_identity": True,
        },
    }
    return with_verification(artifact)


def write_or_check(repo_root: Path, output: Path, check: bool) -> int:
    rendered = build(repo_root, (repo_root / DEFAULT_BASELINE), repo_root / DEFAULT_CAPTURE_DIR, repo_root / DEFAULT_SCREENSHOT_DIR)
    expected = rendered.encode("utf-8")
    if check:
        if not output.is_file() or output.read_bytes() != expected:
            print(f"generated browser-fit summary differs: {output}", file=sys.stderr)
            return 1
        print(f"{output}: OK")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    if not output.is_file() or output.read_bytes() != expected:
        output.write_bytes(expected)
    print(f"wrote {output}")
    return 0


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the deterministic summary differs")
    parser.add_argument("--output", type=Path, default=None, help="summary output path")
    args = parser.parse_args(argv)
    repo_root = Path(__file__).resolve().parents[1]
    output = (args.output or repo_root / DEFAULT_OUTPUT).resolve()
    return write_or_check(repo_root, output, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
